---
- name: 
  hosts: all
  become: true
  tasks:
  - name: stop httpd service
    service:
      name: httpd 
      state: started
    when: ansible_os_family == "RedHat"

  - name: uninstall httpd
    yum: 
      name: httpd 
      state: removed
    when: ansible_os_family ==  "RedHat"
  - name: stop httpd service
    service:
       name: apache2 
       state: stopped
    when: ansible_os_family == "Debian"

  - name: uninstall httpd
    apt:  
      name: apache2 
      state: absent
    when: ansible_os_family ==  "RedHat"
